In [13]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#-------------------------------------------------------------------------------------------
#loading the dataset
retail_df = pd.read_excel("/Users/manesh/Documents/Manesh /Masters/Portfolios/uk-retail-customer-analytics/Data/Online Retail.xlsx")
#-------------------------------------------------------------------------------------------

#examin the dataset data strutre

#preview first 5 rows
display(retail_df.head())

print()

#preview last 5 rows
display(retail_df.tail())

print()

#examin dataset dimensions
print("dataset shape: ", retail_df.shape)
print("dataset num of rows", retail_df.shape[0])
print("dataset num of cols",retail_df.shape[1] )

print()

#examin the col names
print("\nColumn names: ")
print(retail_df.columns.tolist)

print()
#-------------------------------------------------------------------------------------------
#examin the data types and the non-null count of the dataset
print("\nDataset Information: ")
retail_df.info()

print()

#dataset datatypes
print("\nDataset datatypes: ")
print(retail_df.dtypes)

print()
#-------------------------------------------------------------------------------------------
#statistical summary of the dataset
display(retail_df.describe())

print()

#statistical summary including categorical columns
display(retail_df.describe(include="all").T)

print()
#-------------------------------------------------------------------------------------------
#check the number unique values in each column 
unique_values = retail_df.nunique().sort_values

print(unique_values)

#checking the unique values of each columns 

uniqe_description = retail_df["Description"].unique()
unique_stockcode = retail_df["StockCode"].unique()
unique_country = retail_df["Country"].unique()

print("\nUnique descriptions: ")
print(uniqe_description)

print("\nUnique stockcodes: ")
print(unique_stockcode)

print("\nunique country: ")
print(unique_country)

#check unique values with their frequencies 
unique_description_freq = retail_df["Description"].value_counts()
unique_stockcode_freq = retail_df["StockCode"].value_counts()
unique_country_freq = retail_df["Country"].unique()

print("\nUnique descriptions frequencies:")
print(unique_description_freq)

print("\nUnique stockcodes frequencies:")
print(unique_stockcode_freq)

print("\nUnique Country frequencies: ")
print(unique_country_freq)

#check propotion of unique value frequencies 
desc_freq_prop = retail_df["Description"].value_counts(normalize= True)
stockcode_freq_prop = retail_df["StockCode"].value_counts(normalize= True)
country_freq_prop = retail_df["Country"].value_counts(normalize= True)

print("\nUnique descriptions frequencies proportions:")
print(desc_freq_prop)

print("\nUnique stockcode frequencies proportions:")
print(stockcode_freq_prop)

print("\nUnique country frequencies proportions:")
print(country_freq_prop)

#Cardinality summary of dataset
cardinality_summary = pd.DataFrame(
    {
        "Data Type": retail_df.dtypes,
        "Unique Values" : retail_df.nunique(),
        "Missing Values" : retail_df.isnull().sum()

    }
) 

cardinality_summary = cardinality_summary.sort_values(
    by = "Unique Values"
)

print("\nCardinality Summary: ")
display(cardinality_summary)

#-------------------------------------------------------------------------------------------
#Missing values Identification =================================================

#checking missing values per column
missing_values_per_col = retail_df.isnull().sum()

print("\nMissing Values Per Columns: ")
print(missing_values_per_col)

#missing value percentage per column
miss_val_per = retail_df.isnull().sum() / len(retail_df) *100

print("\nMissing Value Percentage per column: ")
print(miss_val_per)

#missing value summary 
missing_summary = pd.DataFrame(
    {
        "Missing_Count" : retail_df.isnull().sum(),
        "Missing_Percentage" : (
            miss_val_per
        )
    }
)

#show the columns containing missing values 
missing_summary = missing_summary [
    missing_summary["Missing_Count"] > 0
]

#Sort highest to Lowest 
missing_summary = missing_summary.sort_values(
    by="Missing_Percentage", 
    ascending = False
)

print("\nMisisng Value Summary: ")
display(missing_summary)

#Check the total missing value count of the dataset 
total_missing = retail_df.isnull().sum().sum()
print("Total Missing Values are : ", total_missing)

#final check on dataset contains any missing value 
Any_miss_val_check = retail_df.isnull().values.any()
print("Any missing values: ", Any_miss_val_check)

#count the rows contains at least one missing value
rows_with_missing = retail_df.isnull().any(axis=1).sum()
print("Rows with missing: ", rows_with_missing)

#handling missing values -----------------------------------
# Fill missing Description values
retail_df["Description"].fillna("Unknown")

#remove rows with missing customer IDs
retail_df = retail_df.dropna(subset=["CustomerID"])

#reset dataset index after dropping rows 
retail_df = retail_df.reset_index(drop=True)

#Validation of the missing values handling
print("\nMissing Values After Handling: ")
print(retail_df.isnull().sum())


print("\nDataset shape after handling missing values: ")
print(retail_df.shape)

#Handling duplicate values -----------------------------------

#Count duplicated rows in dataset

duplicate_rows_count = retail_df.duplicated().sum()
print("\nNumber of duplicated rows in the dataset: ", duplicate_rows_count)

#Percentage of duplicated rows in the datset 
duplicate_percentage = (
    duplicate_rows_count / len(retail_df)) * 100
print(
    "\nPercentage of duplicated rows in the dataset: ",
       round(duplicate_percentage, 2),
       "%"
       )

#inspect all the copies of duplicated rows in the dataset 
duplicated_rows = retail_df[
    retail_df.duplicated(keep=False)
]

display(duplicated_rows.sort_values(
    by = ["InvoiceNo", "StockCode", "CustomerID"]

).head(50))

#figure out the exact transactions duplicated in the dataset 
transaction_duplicates = retail_df[
    retail_df.duplicated(
        subset = [
            "InvoiceNo",
            "StockCode", 
            "CustomerID"
        ], 
        keep=False
    )
]

display(
    transaction_duplicates.sort_values(
        ["InvoiceNo", "StockCode", "CustomerID"]
    ).head(50)
)

#remove exact duplicated transactions from the dataset 
rows_before = len(retail_df)

retail_df = (
    retail_df.drop_duplicates(keep="first")
    .reset_index(drop=True)
)

rows_after = len(retail_df)

print("Rows Removed:", rows_before - rows_after)
print("Remaining duplicates: ", retail_df. duplicated().sum())

#Business Rule Validation of the dataset -----------------------------------

#1. Quantity Validation 

print("Minimum Quantity: ", retail_df["Quantity"].min())
print("Maximum Quantity: ", retail_df["Quantity"].max())

print("Negative Quantity", 
    (retail_df["Quantity"] < 0).sum()
    )

print("Negative Quantity", 
    (retail_df["Quantity"] == 0).sum()
    )

print("Possitive Quantity", 
    (retail_df["Quantity"] > 0).sum()
    )

#inspect problematic/special cases

quality_issues = retail_df[
    retail_df["Quantity"] <= 0
]

print("\nQuality Issues: ")
display(quality_issues.head(20))

#Unit Price Validation 
print("Minimum Unit Price: ", retail_df["UnitPrice"].min())

print("Maximum Unit Price ", retail_df["UnitPrice"].max())

print("Negative Unit Price ", (retail_df["UnitPrice"] < 0).sum())

print("Zero Unit Price ", (retail_df["UnitPrice"] == 0).sum())

#Inspect the issues of the unit price column 

price_issues = retail_df [
    retail_df["UnitPrice"] <= 0 
]

display(price_issues.head(20))


# validation of Customer ID
print("Missing Customer ID: ", retail_df["CustomerID"].isnull().sum())


print("Unique Customer ID: ", retail_df["CustomerID"].nunique())

#fixing the customer ID Data type from float to integer 

retail_df["CustomerID"] = retail_df["CustomerID"].astype("Int64")

#inpect the customer ID Range

print("Minimum Customer ID: ", retail_df["CustomerID"].min())

print("Maximum Customer ID", retail_df["CustomerID"].max())

#Validate the Invoice Date column 

#Ensure the column is in datetime format

retail_df["InvoiceDate"] = pd.to_datetime(retail_df["InvoiceDate"],
                                          errors="coerce")

print(
    "Earliest Transaction Date: ", retail_df["InvoiceDate"].min()
)

print(
    "Latest Transaction Date: ", retail_df["InvoiceDate"].max()
)

print(
    "Invalid Transaction Dates: ", retail_df["InvoiceDate"].isnull().sum()
)

#Validate the Stockcode column 

print(
    "Missing StockCode: ", retail_df["StockCode"].isnull().sum()
)

print(
    "Unique StockCode: ", retail_df["StockCode"].nunique()
)

display(
    retail_df["StockCode"].value_counts().head(20)
)

#Validate the Description Column
print(
    "Missing Description: ", retail_df["Description"].isnull().sum()
)

print(
    "Unknown Description: ", (retail_df["Description"] == "Unknown").sum()
)

print(
    "Unique Description: ", retail_df["Description"].nunique()
)

#remove whitespace in the decsription column 

whitespace_issues = (
    retail_df["Description"].astype(str).str.strip().eq("")
.sum() )

print("Descriptions with whitespaces: ", whitespace_issues)

#Validate Country Column

print(
    "Missing Countries: ", 
    retail_df["Country"].isnull().sum()

)

print(
    "Countries Count: ", retail_df["Country"].nunique()
)

print(
    retail_df["Country"].value_counts().head(20)
)

# check inconsistent labels, whitespace or suspicious values

print(
    "Inconsistent Country Labels,  whitespace or suspicious values: ", 
    (retail_df["Country"].str.strip()) 
)

# business rule validation summary

business_rules = pd.DataFrame({

   "Rule": [
        "Quantity < 0",
        "Quantity = 0",
        "UnitPrice < 0",
        "UnitPrice = 0",
        "Missing CustomerID",
        "Missing StockCode",
        "Missing InvoiceDate",
        "Missing Country",
        "Unknown Description",
    ],
    "Records": [
        (retail_df["Quantity"] < 0).sum(),
        (retail_df["Quantity"] == 0).sum(),
        (retail_df["UnitPrice"] < 0).sum(),
        (retail_df["UnitPrice"] == 0).sum(),
        retail_df["CustomerID"].isnull().sum(),
        retail_df["StockCode"].isnull().sum(),
        retail_df["InvoiceDate"].isnull().sum(),
        retail_df["Country"].isnull().sum(),
        (retail_df["Description"] == "Unknown").sum(),
    ]
}

)

display(business_rules)

#Cancellation / Return Validation Analysis 

# 1. Identify cancellation transactions

cancellation_mark = (
    retail_df["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
)

cancelled_transactions = retail_df[cancellation_mark]

print(
    "Cancellation Transaction Rows: ",
    len(cancelled_transactions)
)

display(cancelled_transactions.head(20))

#Calculate cancellation transaction percentage 

cancellation_percentage = (
    len(cancelled_transactions) / len(retail_df)
) * 100

print(
    "Calculation Percentage: ",
    round(cancellation_percentage, 2),
    "%"
)

#check quantities of cancellation transactions 

print(
   "Cancellation rows with negative quantities:  ", 
    (
        cancelled_transactions["Quantity"] < 0 
    ).sum()
)

print(
    "Cancellation rows with zero quantities: ",
    (
        cancelled_transactions["Quantity"] == 0 
    ).sum()
)

print(
    "Cancellation rows with positive quantities: ",
    (
        cancelled_transactions["Quantity"] > 0
    ).sum()
)

# reverse check - Does it have negative Quantity?, Does the InvoiceNo begin with C?


#identify all the negative quantity transactions
negative_quantity_transactions = retail_df[
    retail_df["Quantity"] < 0 
]

print(
    "Total negative quantity rows: ",
    len(negative_quantity_transactions)
)

#Check for negative quantities WITHOUT cancellation invoice


negative_without_cancellation = retail_df[
    (retail_df["Quantity"] < 0 )
    &
    (~cancellation_mark)
]

print(
   "Negative quantities without C invoice: ",
    len(negative_without_cancellation)
)

display(negative_without_cancellation.head(20))


#Cross check cancellation status and quantity

cancellation_validation = pd.crosstab(
    cancellation_mark,
    retail_df["Quantity"] < 0, 
    rownames= ["Cancellation Invoice"],
    colnames = ["Negative Quantity"]
)

display(cancellation_validation)

#create a transaction-status feature
retail_df["TransactionStatus"] = np.where(
    retail_df["InvoiceNo"]
    .astype(str)
    .str.startswith("C"),
    "Cancelled",
    "Completed"
)

retail_df["TransactionStatus"].value_counts()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

dataset shape:  (541909, 8)
dataset num of rows 541909
dataset num of cols 8


Column names:
<bound method IndexOpsMixin.tolist of Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')>


Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB


Dataset datatypes:
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
InvoiceNo,541909.0,25900.0,573585.0,1114.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockCode,541909,4070,85123A,2313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Description,540455,4223,WHITE HANGING HEART T-LIGHT HOLDER,2369,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,541909.0,NaN,NaN,NaN,9.55225,-80995.0,1.0,3.0,10.0,80995.0,218.081158
InvoiceDate,541909,NaN,NaN,NaN,2011-07-04 13:34:57.156386048,2010-12-01 08:26:00,2011-03-28 11:34:00,2011-07-19 17:17:00,2011-10-19 11:27:00,2011-12-09 12:50:00,NaN
UnitPrice,541909.0,NaN,NaN,NaN,4.611114,-11062.06,1.25,2.08,4.13,38970.0,96.759853
CustomerID,406829.0,NaN,NaN,NaN,15287.69057,12346.0,13953.0,15152.0,16791.0,18287.0,1713.600303
Country,541909,38,United Kingdom,495478,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<bound method Series.sort_values of InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64>

Unique descriptions:
['WHITE HANGING HEART T-LIGHT HOLDER' 'WHITE METAL LANTERN'
 'CREAM CUPID HEARTS COAT HANGER' ... 'lost'
 'CREAM HANGING HEART T-LIGHT HOLDER' 'PAPER CRAFT , LITTLE BIRDIE']

Unique stockcodes:
['85123A' 71053 '84406B' ... '90214U' '47591b' 23843]

unique country:
['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']

Unique descriptions frequencies:
Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
                                      ...
Marked as 23343                          1
20713                                    1
HEAVENS SCENT FRAGRANCE OILS ASSTD       1
BLUE DROP EARRINGS W BEAD CLUSTER        1
PURPLE ANEMONE ARTIFICIAL FLOWER         1
Name: count, Length: 4223, dtype: int64

Unique stockcodes frequencies:
StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
23664        1
23617        1
90214U       1
47591b       1
23602        1
Name: count, Length: 4070, dtype: int64

Unique Country frequencies:
['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']

Unique descriptions frequencies proportions:
Description
WHITE HANGING HEART T-LIGHT HOLDER    0.004383
REGENCY CAKESTAND 3 TIER              0.004071
JUMBO BAG RED RETROSPOT               0.003995
PARTY BUNTING                         0.003195
LUNCH BAG RED RETROSPOT               0.003031
                                        ...
Marked as 23343                       0.000002
20713                                 0.000002
HEAVENS SCENT FRAGRANCE OILS ASSTD    0.000002
BLUE DROP EARRINGS W BEAD CLUSTER     0.000002
PURPLE ANEMONE ARTIFICIAL FLOWER      0.000002
Name: proportion, Length: 4223, dtype: float64

Unique stockcode frequencies proportions:
StockCode
85123A    0.004268
22423     0.004065
85099B    0.003984
47566     0.003187
20725     0.003024
            ...
23664     0.000002
23617     0.000002
90214U    0.000002
47591b    0.000002
23602     0.000002
Name: proportion, Length: 4070, dtype: float64

Unique country frequencies proportions:
Country
United Kingdom          0.914320
Germany                 0.017521
France                  0.015790
EIRE                    0.015124
Spain                   0.004674
Netherlands             0.004375
Belgium                 0.003818
Switzerland             0.003694
Portugal                0.002803
Australia               0.002323
Norway                  0.002004
Italy                   0.001482
Channel Islands         0.001399
Finland                 0.001283
Cyprus                  0.001148
Sweden                  0.000853
Unspecified             0.000823
Austria                 0.000740
Denmark                 0.000718
Japan                   0.000661
Poland                  0.000629
Israel                  0.000548
USA                     0.000537
Hong Kong               0.000531
Singapore               0.000423
Iceland                 0.000336
Canada                  0.000279
Greece                  0.000269
Malta                   0.000234
United Arab Emirates    0.000125
European Community      0.000113
RSA                     0.000107
Lebanon                 0.000083
Lithuania               0.000065
Brazil                  0.000059
Czech Republic          0.000055
Bahrain                 0.000035
Saudi Arabia            0.000018
Name: proportion, dtype: float64

Cardinality Summary:

                  Data Type  Unique Values  Missing Values
Country              object             38               0
Quantity              int64            722               0
UnitPrice           float64           1630               0
StockCode            object           4070               0
Description          object           4223            1454
CustomerID          float64           4372          135080
InvoiceDate  datetime64[ns]          23260               0
InvoiceNo            object          25900               0

Missing Values Per Columns:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Missing Value Percentage per column:
InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

Misisng Value Summary:

             Missing_Count  Missing_Percentage
CustomerID          135080           24.926694
Description           1454            0.268311

Total Missing Values are :  136534
Any missing values:  True
Rows with missing:  135080

Missing Values After Handling:
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

Dataset shape after handling missing values:
(406829, 8)

Number of duplicated rows in the dataset:  5225

Percentage of duplicated rows in the dataset:  1.28 %

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
611,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
603,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
605,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
615,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
620,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
756,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,2010-12-01 12:15:00,1.65,15983.0,United Kingdom
757,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,2010-12-01 12:15:00,1.65,15983.0,United Kingdom
807,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,2010-12-01 12:23:00,2.95,17968.0,United Kingdom
851,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,2010-12-01 12:23:00,2.95,17968.0,United Kingdom
828,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968.0,United Kingdom
830,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968.0,United Kingdom
858,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968.0,United Kingdom
812,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,2010-12-01 12:23:00,0.85,17968.0,United Kingdom
834,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,2010-12-01 12:23:00,0.85,17968.0,United Kingdom
889,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,2010-12-01 12:31:00,2.55,17897.0,United Kingdom
890,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,2010-12-01 12:31:00,2.55,17897.0,United Kingdom
1035,536522,21121,SET/10 RED POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1060,536522,21121,SET/10 RED POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1061,536522,21122,SET/10 PINK POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1066,536522,21122,SET/10 PINK POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1135,536528,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,1,2010-12-01 13:17:00,1.95,15525.0,United Kingdom
1168,536528,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,1,2010-12-01 13:17:00,1.95,15525.0,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
113,536381,71270,PHOTO CLIP LINE,1,2010-12-01 09:41:00,1.25,15311.0,United Kingdom
125,536381,71270,PHOTO CLIP LINE,3,2010-12-01 09:41:00,1.25,15311.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
491,536409,85116,BLACK CANDELABRA T-LIGHT HOLDER,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
502,536409,85116,BLACK CANDELABRA T-LIGHT HOLDER,5,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
483,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,3,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
498,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,1,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
525,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,2,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
561,536412,21738,COSY SLIPPER SHOES SMALL RED,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
571,536412,21738,COSY SLIPPER SHOES SMALL RED,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
585,536412,21738,COSY SLIPPER SHOES SMALL RED,5,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
562,536412,22077,6 RIBBONS RUSTIC CHARM,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
570,536412,22077,6 RIBBONS RUSTIC CHARM,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
577,536412,22077,6 RIBBONS RUSTIC CHARM,7,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
575,536412,22144,CHRISTMAS CRAFT LITTLE FRIENDS,2,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
595,536412,22144,CHRISTMAS CRAFT LITTLE FRIENDS,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
573,536412,22243,5 HOOK HANGER RED MAGIC TOADSTOOL,6,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
576,536412,22243,5 HOOK HANGER RED MAGIC TOADSTOOL,3,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
583,536412,22243,5 HOOK HANGER RED MAGIC TOADSTOOL,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
592,536412,22273,FELTCRAFT DOLL MOLLY,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
567,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
559,536412,22759,SET OF 3 NOTEBOOKS IN PARCEL,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
579,536412,22759,SET OF 3 NOTEBOOKS IN PARCEL,5,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
611,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

Rows Removed: 5225
Remaining duplicates:  0
Minimum Quantity:  -80995
Maximum Quantity:  80995
Negative Quantity 8872
Negative Quantity 0
Possitive Quantity 392732

Quality Issues:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
915,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1404,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1405,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1406,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1407,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1408,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1409,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1410,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1411,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1412,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1413,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany

Minimum Unit Price:  0.0
Maximum Unit Price  38970.0
Negative Unit Price  0
Zero Unit Price  40

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
6842,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647.0,Germany
22619,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,2010-12-16 14:36:00,0.0,16560.0,United Kingdom
25551,539722,22423,REGENCY CAKESTAND 3 TIER,10,2010-12-21 13:45:00,0.0,14911.0,EIRE
29374,540372,22090,PAPER BUNTING RETROSPOT,24,2011-01-06 16:41:00,0.0,13081.0,United Kingdom
29376,540372,22553,PLASTERS IN TIN SKULLS,24,2011-01-06 16:41:00,0.0,13081.0,United Kingdom
34903,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,2011-01-13 15:10:00,0.0,15107.0,United Kingdom
54482,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,2011-02-10 13:08:00,0.0,17560.0,United Kingdom
86760,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,2011-03-23 10:25:00,0.0,13239.0,United Kingdom
93947,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,2011-03-30 12:45:00,0.0,13113.0,United Kingdom
98634,548871,22162,HEART GARLAND RUSTIC PADDED,2,2011-04-04 14:42:00,0.0,14410.0,United Kingdom
108583,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,2011-04-14 18:57:00,0.0,12457.0,Switzerland
130286,553000,47566,PARTY BUNTING,4,2011-05-12 15:21:00,0.0,17667.0,United Kingdom
138864,554037,22619,SET OF 6 SOLDIER SKITTLES,80,2011-05-20 14:13:00,0.0,12415.0,Australia
197297,561284,22167,OVAL WALL MIRROR DIAMANTE,1,2011-07-26 12:24:00,0.0,16818.0,United Kingdom
199859,561669,22960,JAM MAKING SET WITH JARS,11,2011-07-28 17:09:00,0.0,12507.0,Spain
202393,561916,M,Manual,1,2011-08-01 11:44:00,0.0,15581.0,United Kingdom
211834,562973,23157,SET OF 6 NATIVITY MAGNETS,240,2011-08-11 11:42:00,0.0,14911.0,EIRE
226959,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,2011-08-26 14:19:00,0.0,14646.0,Netherlands
226960,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,2011-08-26 14:19:00,0.0,14646.0,Netherlands
226961,564651,22955,36 FOIL STAR CAKE CASES,144,2011-08-26 14:19:00,0.0,14646.0,Netherlands

Missing Customer ID:  0
Unique Customer ID:  4372
Minimum Customer ID:  12346
Maximum Customer ID 18287
Earliest Transaction Date:  2010-12-01 08:26:00
Latest Transaction Date:  2011-12-09 12:50:00
Invalid Transaction Dates:  0
Missing StockCode:  0
Unique StockCode:  3684

StockCode
85123A    2065
22423     1894
85099B    1659
47566     1409
84879     1405
20725     1346
22720     1224
POST      1196
22197     1110
23203     1108
20727     1099
22383     1083
21212     1062
23298     1033
23209     1031
22086     1013
22382     1006
20728     1000
22469      990
22457      989
Name: count, dtype: int64

Missing Description:  0
Unknown Description:  0
Unique Description:  3896
Descriptions with whitespaces:  0
Missing Countries:  0
Countries Count:  37
Country
United Kingdom     356728
Germany              9480
France               8475
EIRE                 7475
Spain                2528
Netherlands          2371
Belgium              2069
Switzerland          1877
Portugal             1471
Australia            1258
Norway               1086
Italy                 803
Channel Islands       757
Finland               695
Cyprus                611
Sweden                461
Austria               401
Denmark               389
Japan                 358
Poland                341
Name: count, dtype: int64
Inconsistent Country Labels,  whitespace or suspicious values:  0         United Kingdom
1         United Kingdom
2         United Kingdom
3         United Kingdom
4         United Kingdom
               ...
401599            France
401600            France
401601            France
401602            France
401603            France
Name: Country, Length: 401604, dtype: object

                  Rule  Records
0         Quantity < 0     8872
1         Quantity = 0        0
2        UnitPrice < 0        0
3        UnitPrice = 0       40
4   Missing CustomerID        0
5    Missing StockCode        0
6  Missing InvoiceDate        0
7      Missing Country        0
8  Unknown Description        0

Cancellation Transaction Rows:  8872

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548,United Kingdom
915,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897,United Kingdom
1404,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841,United Kingdom
1405,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841,United Kingdom
1406,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472,Germany
1407,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472,Germany
1408,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472,Germany
1409,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472,Germany
1410,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472,Germany
1411,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472,Germany
1412,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472,Germany
1413,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472,Germany

Calculation Percentage:  2.21 %
Cancellation rows with negative quantities:   8872
Cancellation rows with zero quantities:  0
Cancellation rows with positive quantities:  0
Total negative quantity rows:  8872
Negative quantities without C invoice:  0

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

Negative Quantity      False  True
Cancellation Invoice
False                 392732      0
True                       0   8872

TransactionStatus
Completed    392732
Cancelled      8872
Name: count, dtype: int64